### ISSUE TITLE
how to declare remote machine/connection info

### ISSUE THREAD

**Issue by aplowman** [hpcflow/hpcflow_execution#21]
In the hpcflow/matflow config file:
```yaml
    config:
      machine: 
        name: MyDesktop
        schedulers:
          - type: direct
          - type: SGE
            is_default: True
   
      connections:
        - to: CSF3
          type: SCP
        - to: dropbox
          type: cloud
        - to: CSF4
        - to: laptop        
```

Workflow tasks will specify a `scratch` value and optionally a `scheduler` value, e.g.:

```yaml
tasks:
  - schemas: [dummy_task_1]

    resources:
      scratch: CSF3
      scheduler: SGE
```
